import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Alphabet from './models/Alphabet';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/Academicians';

// Helper function to generate placeholder images
const getLetterImage = (letter: string, language: string) => {
  return `https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=200&q=80&text=${letter}`;
};

const getNumberImage = (num: string) => {
  return `https://images.unsplash.com/photo-1509228468518-180dd4864904?w=200&q=80&text=${num}`;
};

const alphabetData = [
  // ENGLISH
  {
    language: 'English',
    langCode: 'en-US',
    audioVerified: true,
    description: 'Learn the English alphabet (A-Z) and numbers 1-20. English uses the Latin alphabet with 26 letters.',
    specialNotes: 'English pronunciation can vary, but these are the standard letter names.',
    letters: [
      { char: 'A', pronunciation: 'ay', image: getLetterImage('A', 'english') },
      { char: 'B', pronunciation: 'bee', image: getLetterImage('B', 'english') },
      { char: 'C', pronunciation: 'see', image: getLetterImage('C', 'english') },
      { char: 'D', pronunciation: 'dee', image: getLetterImage('D', 'english') },
      { char: 'E', pronunciation: 'ee', image: getLetterImage('E', 'english') },
      { char: 'F', pronunciation: 'eff', image: getLetterImage('F', 'english') },
      { char: 'G', pronunciation: 'jee', image: getLetterImage('G', 'english') },
      { char: 'H', pronunciation: 'aych', image: getLetterImage('H', 'english') },
      { char: 'I', pronunciation: 'eye', image: getLetterImage('I', 'english') },
      { char: 'J', pronunciation: 'jay', image: getLetterImage('J', 'english') },
      { char: 'K', pronunciation: 'kay', image: getLetterImage('K', 'english') },
      { char: 'L', pronunciation: 'ell', image: getLetterImage('L', 'english') },
      { char: 'M', pronunciation: 'emm', image: getLetterImage('M', 'english') },
      { char: 'N', pronunciation: 'enn', image: getLetterImage('N', 'english') },
      { char: 'O', pronunciation: 'oh', image: getLetterImage('O', 'english') },
      { char: 'P', pronunciation: 'pee', image: getLetterImage('P', 'english') },
      { char: 'Q', pronunciation: 'kyoo', image: getLetterImage('Q', 'english') },
      { char: 'R', pronunciation: 'arr', image: getLetterImage('R', 'english') },
      { char: 'S', pronunciation: 'ess', image: getLetterImage('S', 'english') },
      { char: 'T', pronunciation: 'tee', image: getLetterImage('T', 'english') },
      { char: 'U', pronunciation: 'yoo', image: getLetterImage('U', 'english') },
      { char: 'V', pronunciation: 'vee', image: getLetterImage('V', 'english') },
      { char: 'W', pronunciation: 'double-you', image: getLetterImage('W', 'english') },
      { char: 'X', pronunciation: 'ex', image: getLetterImage('X', 'english') },
      { char: 'Y', pronunciation: 'why', image: getLetterImage('Y', 'english') },
      { char: 'Z', pronunciation: 'zee', image: getLetterImage('Z', 'english') },
    ],
    numbers: [
      { char: '1', text: 'one', pronunciation: 'wun', image: getNumberImage('1') },
      { char: '2', text: 'two', pronunciation: 'too', image: getNumberImage('2') },
      { char: '3', text: 'three', pronunciation: 'three', image: getNumberImage('3') },
      { char: '4', text: 'four', pronunciation: 'for', image: getNumberImage('4') },
      { char: '5', text: 'five', pronunciation: 'feyev', image: getNumberImage('5') },
      { char: '6', text: 'six', pronunciation: 'siks', image: getNumberImage('6') },
      { char: '7', text: 'seven', pronunciation: 'SEV-en', image: getNumberImage('7') },
      { char: '8', text: 'eight', pronunciation: 'ayt', image: getNumberImage('8') },
      { char: '9', text: 'nine', pronunciation: 'neyen', image: getNumberImage('9') },
      { char: '10', text: 'ten', pronunciation: 'ten', image: getNumberImage('10') },
      { char: '11', text: 'eleven', pronunciation: 'ee-LEV-en', image: getNumberImage('11') },
      { char: '12', text: 'twelve', pronunciation: 'twelv', image: getNumberImage('12') },
      { char: '13', text: 'thirteen', pronunciation: 'thur-TEEN', image: getNumberImage('13') },
      { char: '14', text: 'fourteen', pronunciation: 'for-TEEN', image: getNumberImage('14') },
      { char: '15', text: 'fifteen', pronunciation: 'fif-TEEN', image: getNumberImage('15') },
      { char: '16', text: 'sixteen', pronunciation: 'siks-TEEN', image: getNumberImage('16') },
      { char: '17', text: 'seventeen', pronunciation: 'sev-en-TEEN', image: getNumberImage('17') },
      { char: '18', text: 'eighteen', pronunciation: 'ay-TEEN', image: getNumberImage('18') },
      { char: '19', text: 'nineteen', pronunciation: 'neyen-TEEN', image: getNumberImage('19') },
      { char: '20', text: 'twenty', pronunciation: 'TWEN-tee', image: getNumberImage('20') },
    ],
  },

  // SPANISH
  {
    language: 'Spanish',
    langCode: 'es-ES',
    audioVerified: true,
    description: 'Learn the Spanish alphabet (el alfabeto) and numbers 1-20. Spanish has 27 letters including Ñ.',
    specialNotes: 'Spanish includes the unique letter Ñ (eñe). CH and LL were historically considered separate letters.',
    letters: [
      { char: 'A', pronunciation: 'ah', image: getLetterImage('A', 'spanish') },
      { char: 'B', pronunciation: 'beh', image: getLetterImage('B', 'spanish') },
      { char: 'C', pronunciation: 'seh', image: getLetterImage('C', 'spanish') },
      { char: 'D', pronunciation: 'deh', image: getLetterImage('D', 'spanish') },
      { char: 'E', pronunciation: 'eh', image: getLetterImage('E', 'spanish') },
      { char: 'F', pronunciation: 'eh-feh', image: getLetterImage('F', 'spanish') },
      { char: 'G', pronunciation: 'heh', image: getLetterImage('G', 'spanish') },
      { char: 'H', pronunciation: 'ah-cheh', image: getLetterImage('H', 'spanish') },
      { char: 'I', pronunciation: 'ee', image: getLetterImage('I', 'spanish') },
      { char: 'J', pronunciation: 'ho-tah', image: getLetterImage('J', 'spanish') },
      { char: 'K', pronunciation: 'kah', image: getLetterImage('K', 'spanish') },
      { char: 'L', pronunciation: 'eh-leh', image: getLetterImage('L', 'spanish') },
      { char: 'M', pronunciation: 'eh-meh', image: getLetterImage('M', 'spanish') },
      { char: 'N', pronunciation: 'eh-neh', image: getLetterImage('N', 'spanish') },
      { char: 'Ñ', pronunciation: 'eh-nyeh', image: getLetterImage('Ñ', 'spanish') },
      { char: 'O', pronunciation: 'oh', image: getLetterImage('O', 'spanish') },
      { char: 'P', pronunciation: 'peh', image: getLetterImage('P', 'spanish') },
      { char: 'Q', pronunciation: 'koo', image: getLetterImage('Q', 'spanish') },
      { char: 'R', pronunciation: 'eh-reh', image: getLetterImage('R', 'spanish') },
      { char: 'S', pronunciation: 'eh-seh', image: getLetterImage('S', 'spanish') },
      { char: 'T', pronunciation: 'teh', image: getLetterImage('T', 'spanish') },
      { char: 'U', pronunciation: 'oo', image: getLetterImage('U', 'spanish') },
      { char: 'V', pronunciation: 'oo-beh', image: getLetterImage('V', 'spanish') },
      { char: 'W', pronunciation: 'dob-leh oo', image: getLetterImage('W', 'spanish') },
      { char: 'X', pronunciation: 'eh-kees', image: getLetterImage('X', 'spanish') },
      { char: 'Y', pronunciation: 'ee gree-eh-gah', image: getLetterImage('Y', 'spanish') },
      { char: 'Z', pronunciation: 'seh-tah', image: getLetterImage('Z', 'spanish') },
    ],
    numbers: [
      { char: '1', text: 'uno', pronunciation: 'OO-no', image: getNumberImage('1') },
      { char: '2', text: 'dos', pronunciation: 'dose', image: getNumberImage('2') },
      { char: '3', text: 'tres', pronunciation: 'trace', image: getNumberImage('3') },
      { char: '4', text: 'cuatro', pronunciation: 'KWA-tro', image: getNumberImage('4') },
      { char: '5', text: 'cinco', pronunciation: 'SEEN-ko', image: getNumberImage('5') },
      { char: '6', text: 'seis', pronunciation: 'SAYce', image: getNumberImage('6') },
      { char: '7', text: 'siete', pronunciation: 'see-EH-teh', image: getNumberImage('7') },
      { char: '8', text: 'ocho', pronunciation: 'OH-cho', image: getNumberImage('8') },
      { char: '9', text: 'nueve', pronunciation: 'NWEH-veh', image: getNumberImage('9') },
      { char: '10', text: 'diez', pronunciation: 'dee-ESS', image: getNumberImage('10') },
      { char: '11', text: 'once', pronunciation: 'ON-seh', image: getNumberImage('11') },
      { char: '12', text: 'doce', pronunciation: 'DOH-seh', image: getNumberImage('12') },
      { char: '13', text: 'trece', pronunciation: 'TREH-seh', image: getNumberImage('13') },
      { char: '14', text: 'catorce', pronunciation: 'kah-TOR-seh', image: getNumberImage('14') },
      { char: '15', text: 'quince', pronunciation: 'KEEN-seh', image: getNumberImage('15') },
      { char: '16', text: 'dieciséis', pronunciation: 'dee-eh-see-SAYSS', image: getNumberImage('16') },
      { char: '17', text: 'diecisiete', pronunciation: 'dee-eh-see-see-EH-teh', image: getNumberImage('17') },
      { char: '18', text: 'dieciocho', pronunciation: 'dee-eh-see-OH-cho', image: getNumberImage('18') },
      { char: '19', text: 'diecinueve', pronunciation: 'dee-eh-see-NWEH-veh', image: getNumberImage('19') },
      { char: '20', text: 'veinte', pronunciation: 'BAYN-teh', image: getNumberImage('20') },
    ],
  },

  // FRENCH
  {
    language: 'French',
    langCode: 'fr-FR',
    audioVerified: true,
    description: 'Learn the French alphabet (l\'alphabet français) and numbers 1-20. French uses accented letters.',
    specialNotes: 'French has accent marks (é, è, ê, ë, à, ù, ç) that modify pronunciation.',
    letters: [
      { char: 'A', pronunciation: 'ah', image: getLetterImage('A', 'french') },
      { char: 'B', pronunciation: 'bay', image: getLetterImage('B', 'french') },
      { char: 'C', pronunciation: 'say', image: getLetterImage('C', 'french') },
      { char: 'D', pronunciation: 'day', image: getLetterImage('D', 'french') },
      { char: 'E', pronunciation: 'uh', image: getLetterImage('E', 'french') },
      { char: 'F', pronunciation: 'eff', image: getLetterImage('F', 'french') },
      { char: 'G', pronunciation: 'zhay', image: getLetterImage('G', 'french') },
      { char: 'H', pronunciation: 'ahsh', image: getLetterImage('H', 'french') },
      { char: 'I', pronunciation: 'ee', image: getLetterImage('I', 'french') },
      { char: 'J', pronunciation: 'zhee', image: getLetterImage('J', 'french') },
      { char: 'K', pronunciation: 'kah', image: getLetterImage('K', 'french') },
      { char: 'L', pronunciation: 'ell', image: getLetterImage('L', 'french') },
      { char: 'M', pronunciation: 'emm', image: getLetterImage('M', 'french') },
      { char: 'N', pronunciation: 'enn', image: getLetterImage('N', 'french') },
      { char: 'O', pronunciation: 'oh', image: getLetterImage('O', 'french') },
      { char: 'P', pronunciation: 'pay', image: getLetterImage('P', 'french') },
      { char: 'Q', pronunciation: 'koo', image: getLetterImage('Q', 'french') },
      { char: 'R', pronunciation: 'air', image: getLetterImage('R', 'french') },
      { char: 'S', pronunciation: 'ess', image: getLetterImage('S', 'french') },
      { char: 'T', pronunciation: 'tay', image: getLetterImage('T', 'french') },
      { char: 'U', pronunciation: 'oo', image: getLetterImage('U', 'french') },
      { char: 'V', pronunciation: 'vay', image: getLetterImage('V', 'french') },
      { char: 'W', pronunciation: 'doo-bluh-vay', image: getLetterImage('W', 'french') },
      { char: 'X', pronunciation: 'eeks', image: getLetterImage('X', 'french') },
      { char: 'Y', pronunciation: 'ee-grek', image: getLetterImage('Y', 'french') },
      { char: 'Z', pronunciation: 'zed', image: getLetterImage('Z', 'french') },
    ],
    numbers: [
      { char: '1', text: 'un', pronunciation: 'uhn', image: getNumberImage('1') },
      { char: '2', text: 'deux', pronunciation: 'duh', image: getNumberImage('2') },
      { char: '3', text: 'trois', pronunciation: 'twah', image: getNumberImage('3') },
      { char: '4', text: 'quatre', pronunciation: 'KAH-truh', image: getNumberImage('4') },
      { char: '5', text: 'cinq', pronunciation: 'sank', image: getNumberImage('5') },
      { char: '6', text: 'six', pronunciation: 'seess', image: getNumberImage('6') },
      { char: '7', text: 'sept', pronunciation: 'set', image: getNumberImage('7') },
      { char: '8', text: 'huit', pronunciation: 'weet', image: getNumberImage('8') },
      { char: '9', text: 'neuf', pronunciation: 'nuhf', image: getNumberImage('9') },
      { char: '10', text: 'dix', pronunciation: 'deess', image: getNumberImage('10') },
      { char: '11', text: 'onze', pronunciation: 'onz', image: getNumberImage('11') },
      { char: '12', text: 'douze', pronunciation: 'dooz', image: getNumberImage('12') },
      { char: '13', text: 'treize', pronunciation: 'trez', image: getNumberImage('13') },
      { char: '14', text: 'quatorze', pronunciation: 'kah-TORZ', image: getNumberImage('14') },
      { char: '15', text: 'quinze', pronunciation: 'kanz', image: getNumberImage('15') },
      { char: '16', text: 'seize', pronunciation: 'sez', image: getNumberImage('16') },
      { char: '17', text: 'dix-sept', pronunciation: 'deess-set', image: getNumberImage('17') },
      { char: '18', text: 'dix-huit', pronunciation: 'deez-weet', image: getNumberImage('18') },
      { char: '19', text: 'dix-neuf', pronunciation: 'deez-nuhf', image: getNumberImage('19') },
      { char: '20', text: 'vingt', pronunciation: 'van', image: getNumberImage('20') },
    ],
  },

  // GERMAN
  {
    language: 'German',
    langCode: 'de-DE',
    audioVerified: true,
    description: 'Learn the German alphabet (das deutsche Alphabet) and numbers 1-20. German includes umlauts.',
    specialNotes: 'German has special characters: Ä, Ö, Ü (umlauts) and ß (Eszett/sharp S).',
    letters: [
      { char: 'A', pronunciation: 'ah', image: getLetterImage('A', 'german') },
      { char: 'B', pronunciation: 'bay', image: getLetterImage('B', 'german') },
      { char: 'C', pronunciation: 'tsay', image: getLetterImage('C', 'german') },
      { char: 'D', pronunciation: 'day', image: getLetterImage('D', 'german') },
      { char: 'E', pronunciation: 'ay', image: getLetterImage('E', 'german') },
      { char: 'F', pronunciation: 'eff', image: getLetterImage('F', 'german') },
      { char: 'G', pronunciation: 'gay', image: getLetterImage('G', 'german') },
      { char: 'H', pronunciation: 'hah', image: getLetterImage('H', 'german') },
      { char: 'I', pronunciation: 'ee', image: getLetterImage('I', 'german') },
      { char: 'J', pronunciation: 'yot', image: getLetterImage('J', 'german') },
      { char: 'K', pronunciation: 'kah', image: getLetterImage('K', 'german') },
      { char: 'L', pronunciation: 'ell', image: getLetterImage('L', 'german') },
      { char: 'M', pronunciation: 'emm', image: getLetterImage('M', 'german') },
      { char: 'N', pronunciation: 'enn', image: getLetterImage('N', 'german') },
      { char: 'O', pronunciation: 'oh', image: getLetterImage('O', 'german') },
      { char: 'P', pronunciation: 'pay', image: getLetterImage('P', 'german') },
      { char: 'Q', pronunciation: 'koo', image: getLetterImage('Q', 'german') },
      { char: 'R', pronunciation: 'air', image: getLetterImage('R', 'german') },
      { char: 'S', pronunciation: 'ess', image: getLetterImage('S', 'german') },
      { char: 'T', pronunciation: 'tay', image: getLetterImage('T', 'german') },
      { char: 'U', pronunciation: 'oo', image: getLetterImage('U', 'german') },
      { char: 'V', pronunciation: 'fow', image: getLetterImage('V', 'german') },
      { char: 'W', pronunciation: 'vay', image: getLetterImage('W', 'german') },
      { char: 'X', pronunciation: 'iks', image: getLetterImage('X', 'german') },
      { char: 'Y', pronunciation: 'oopsilon', image: getLetterImage('Y', 'german') },
      { char: 'Z', pronunciation: 'tset', image: getLetterImage('Z', 'german') },
      { char: 'Ä', pronunciation: 'ay-umlaut', image: getLetterImage('Ä', 'german') },
      { char: 'Ö', pronunciation: 'oh-umlaut', image: getLetterImage('Ö', 'german') },
      { char: 'Ü', pronunciation: 'oo-umlaut', image: getLetterImage('Ü', 'german') },
      { char: 'ß', pronunciation: 'ess-tset', image: getLetterImage('ß', 'german') },
    ],
    numbers: [
      { char: '1', text: 'eins', pronunciation: 'eyents', image: getNumberImage('1') },
      { char: '2', text: 'zwei', pronunciation: 'tsvey', image: getNumberImage('2') },
      { char: '3', text: 'drei', pronunciation: 'dry', image: getNumberImage('3') },
      { char: '4', text: 'vier', pronunciation: 'feer', image: getNumberImage('4') },
      { char: '5', text: 'fünf', pronunciation: 'fuenf', image: getNumberImage('5') },
      { char: '6', text: 'sechs', pronunciation: 'zex', image: getNumberImage('6') },
      { char: '7', text: 'sieben', pronunciation: 'ZEE-ben', image: getNumberImage('7') },
      { char: '8', text: 'acht', pronunciation: 'ahkt', image: getNumberImage('8') },
      { char: '9', text: 'neun', pronunciation: 'noyn', image: getNumberImage('9') },
      { char: '10', text: 'zehn', pronunciation: 'tsayn', image: getNumberImage('10') },
      { char: '11', text: 'elf', pronunciation: 'elf', image: getNumberImage('11') },
      { char: '12', text: 'zwölf', pronunciation: 'tsvuhlf', image: getNumberImage('12') },
      { char: '13', text: 'dreizehn', pronunciation: 'DRY-tsayn', image: getNumberImage('13') },
      { char: '14', text: 'vierzehn', pronunciation: 'FEER-tsayn', image: getNumberImage('14') },
      { char: '15', text: 'fünfzehn', pronunciation: 'FUENF-tsayn', image: getNumberImage('15') },
      { char: '16', text: 'sechzehn', pronunciation: 'ZECH-tsayn', image: getNumberImage('16') },
      { char: '17', text: 'siebzehn', pronunciation: 'ZEEP-tsayn', image: getNumberImage('17') },
      { char: '18', text: 'achtzehn', pronunciation: 'AHK-tsayn', image: getNumberImage('18') },
      { char: '19', text: 'neunzehn', pronunciation: 'NOYN-tsayn', image: getNumberImage('19') },
      { char: '20', text: 'zwanzig', pronunciation: 'TSVAN-tsikh', image: getNumberImage('20') },
    ],
  },

  // CHINESE (Pinyin)
  {
    language: 'Chinese',
    langCode: 'zh-CN',
    audioVerified: true,
    description: 'Learn Chinese Pinyin romanization and numbers 1-20. Pinyin helps with pronunciation of Mandarin Chinese.',
    specialNotes: 'Chinese uses characters (汉字). Pinyin is the romanization system. Tones are crucial for meaning.',
    letters: [
      { char: '一', pronunciation: 'yī', image: getLetterImage('一', 'chinese') },
      { char: '二', pronunciation: 'èr', image: getLetterImage('二', 'chinese') },
      { char: '三', pronunciation: 'sān', image: getLetterImage('三', 'chinese') },
      { char: '四', pronunciation: 'sì', image: getLetterImage('四', 'chinese') },
      { char: '五', pronunciation: 'wǔ', image: getLetterImage('五', 'chinese') },
      { char: '六', pronunciation: 'liù', image: getLetterImage('六', 'chinese') },
      { char: '七', pronunciation: 'qī', image: getLetterImage('七', 'chinese') },
      { char: '八', pronunciation: 'bā', image: getLetterImage('八', 'chinese') },
      { char: '九', pronunciation: 'jiǔ', image: getLetterImage('九', 'chinese') },
      { char: '十', pronunciation: 'shí', image: getLetterImage('十', 'chinese') },
      { char: '你', pronunciation: 'nǐ (you)', image: getLetterImage('你', 'chinese') },
      { char: '好', pronunciation: 'hǎo (good)', image: getLetterImage('好', 'chinese') },
      { char: '我', pronunciation: 'wǒ (I/me)', image: getLetterImage('我', 'chinese') },
      { char: '是', pronunciation: 'shì (is/am/are)', image: getLetterImage('是', 'chinese') },
      { char: '的', pronunciation: 'de (possessive)', image: getLetterImage('的', 'chinese') },
      { char: '人', pronunciation: 'rén (person)', image: getLetterImage('人', 'chinese') },
      { char: '大', pronunciation: 'dà (big)', image: getLetterImage('大', 'chinese') },
      { char: '小', pronunciation: 'xiǎo (small)', image: getLetterImage('小', 'chinese') },
      { char: '天', pronunciation: 'tiān (sky/day)', image: getLetterImage('天', 'chinese') },
      { char: '水', pronunciation: 'shuǐ (water)', image: getLetterImage('水', 'chinese') },
    ],
    numbers: [
      { char: '1', text: '一 (yī)', pronunciation: 'yee', image: getNumberImage('1') },
      { char: '2', text: '二 (èr)', pronunciation: 'ar', image: getNumberImage('2') },
      { char: '3', text: '三 (sān)', pronunciation: 'sahn', image: getNumberImage('3') },
      { char: '4', text: '四 (sì)', pronunciation: 'suh', image: getNumberImage('4') },
      { char: '5', text: '五 (wǔ)', pronunciation: 'woo', image: getNumberImage('5') },
      { char: '6', text: '六 (liù)', pronunciation: 'lee-oh', image: getNumberImage('6') },
      { char: '7', text: '七 (qī)', pronunciation: 'chee', image: getNumberImage('7') },
      { char: '8', text: '八 (bā)', pronunciation: 'bah', image: getNumberImage('8') },
      { char: '9', text: '九 (jiǔ)', pronunciation: 'jee-oh', image: getNumberImage('9') },
      { char: '10', text: '十 (shí)', pronunciation: 'shir', image: getNumberImage('10') },
      { char: '11', text: '十一 (shíyī)', pronunciation: 'shir-yee', image: getNumberImage('11') },
      { char: '12', text: '十二 (shíèr)', pronunciation: 'shir-ar', image: getNumberImage('12') },
      { char: '13', text: '十三 (shísān)', pronunciation: 'shir-sahn', image: getNumberImage('13') },
      { char: '14', text: '十四 (shísì)', pronunciation: 'shir-suh', image: getNumberImage('14') },
      { char: '15', text: '十五 (shíwǔ)', pronunciation: 'shir-woo', image: getNumberImage('15') },
      { char: '16', text: '十六 (shíliù)', pronunciation: 'shir-lee-oh', image: getNumberImage('16') },
      { char: '17', text: '十七 (shíqī)', pronunciation: 'shir-chee', image: getNumberImage('17') },
      { char: '18', text: '十八 (shíbā)', pronunciation: 'shir-bah', image: getNumberImage('18') },
      { char: '19', text: '十九 (shíjiǔ)', pronunciation: 'shir-jee-oh', image: getNumberImage('19') },
      { char: '20', text: '二十 (èrshí)', pronunciation: 'ar-shir', image: getNumberImage('20') },
    ],
  },
  // JAPANESE (Hiragana basics)
  {
    language: 'Japanese',
    langCode: 'ja-JP',
    audioVerified: true,
    description: 'Learn Japanese Hiragana characters and numbers 1-20. Hiragana is one of three Japanese writing systems.',
    specialNotes: 'Japanese uses three writing systems: Hiragana, Katakana, and Kanji. Start with Hiragana for basic words.',
    letters: [
      { char: 'あ', pronunciation: 'a', image: getLetterImage('あ', 'japanese') },
      { char: 'い', pronunciation: 'i', image: getLetterImage('い', 'japanese') },
      { char: 'う', pronunciation: 'u', image: getLetterImage('う', 'japanese') },
      { char: 'え', pronunciation: 'e', image: getLetterImage('え', 'japanese') },
      { char: 'お', pronunciation: 'o', image: getLetterImage('お', 'japanese') },
      { char: 'か', pronunciation: 'ka', image: getLetterImage('か', 'japanese') },
      { char: 'き', pronunciation: 'ki', image: getLetterImage('き', 'japanese') },
      { char: 'く', pronunciation: 'ku', image: getLetterImage('く', 'japanese') },
      { char: 'け', pronunciation: 'ke', image: getLetterImage('け', 'japanese') },
      { char: 'こ', pronunciation: 'ko', image: getLetterImage('こ', 'japanese') },
      { char: 'さ', pronunciation: 'sa', image: getLetterImage('さ', 'japanese') },
      { char: 'し', pronunciation: 'shi', image: getLetterImage('し', 'japanese') },
      { char: 'す', pronunciation: 'su', image: getLetterImage('す', 'japanese') },
      { char: 'せ', pronunciation: 'se', image: getLetterImage('せ', 'japanese') },
      { char: 'そ', pronunciation: 'so', image: getLetterImage('そ', 'japanese') },
      { char: 'た', pronunciation: 'ta', image: getLetterImage('た', 'japanese') },
      { char: 'ち', pronunciation: 'chi', image: getLetterImage('ち', 'japanese') },
      { char: 'つ', pronunciation: 'tsu', image: getLetterImage('つ', 'japanese') },
      { char: 'て', pronunciation: 'te', image: getLetterImage('て', 'japanese') },
      { char: 'と', pronunciation: 'to', image: getLetterImage('と', 'japanese') },
    ],
    numbers: [
      { char: '1', text: '一 (ichi)', pronunciation: 'ee-chee', image: getNumberImage('1') },
      { char: '2', text: '二 (ni)', pronunciation: 'nee', image: getNumberImage('2') },
      { char: '3', text: '三 (san)', pronunciation: 'sahn', image: getNumberImage('3') },
      { char: '4', text: '四 (yon)', pronunciation: 'yohn', image: getNumberImage('4') },
      { char: '5', text: '五 (go)', pronunciation: 'goh', image: getNumberImage('5') },
      { char: '6', text: '六 (roku)', pronunciation: 'roh-koo', image: getNumberImage('6') },
      { char: '7', text: '七 (nana)', pronunciation: 'nah-nah', image: getNumberImage('7') },
      { char: '8', text: '八 (hachi)', pronunciation: 'hah-chee', image: getNumberImage('8') },
      { char: '9', text: '九 (kyuu)', pronunciation: 'kyoo', image: getNumberImage('9') },
      { char: '10', text: '十 (juu)', pronunciation: 'joo', image: getNumberImage('10') },
      { char: '11', text: '十一 (juuichi)', pronunciation: 'joo-ee-chee', image: getNumberImage('11') },
      { char: '12', text: '十二 (juuni)', pronunciation: 'joo-nee', image: getNumberImage('12') },
      { char: '13', text: '十三 (juusan)', pronunciation: 'joo-sahn', image: getNumberImage('13') },
      { char: '14', text: '十四 (juuyon)', pronunciation: 'joo-yohn', image: getNumberImage('14') },
      { char: '15', text: '十五 (juugo)', pronunciation: 'joo-goh', image: getNumberImage('15') },
      { char: '16', text: '十六 (juuroku)', pronunciation: 'joo-roh-koo', image: getNumberImage('16') },
      { char: '17', text: '十七 (juunana)', pronunciation: 'joo-nah-nah', image: getNumberImage('17') },
      { char: '18', text: '十八 (juuhachi)', pronunciation: 'joo-hah-chee', image: getNumberImage('18') },
      { char: '19', text: '十九 (juukyuu)', pronunciation: 'joo-kyoo', image: getNumberImage('19') },
      { char: '20', text: '二十 (nijuu)', pronunciation: 'nee-joo', image: getNumberImage('20') },
    ],
  },
  // ARABIC
  {
    language: 'Arabic',
    langCode: 'ar-SA',
    audioVerified: true,
    description: 'Learn the Arabic alphabet (28 letters) and numbers 1-20. Arabic is written from right to left.',
    specialNotes: 'Arabic script is written from right to left. Letters change shape based on position in a word.',
    letters: [
      { char: 'ا', pronunciation: 'alif', image: getLetterImage('ا', 'arabic') },
      { char: 'ب', pronunciation: 'ba', image: getLetterImage('ب', 'arabic') },
      { char: 'ت', pronunciation: 'ta', image: getLetterImage('ت', 'arabic') },
      { char: 'ث', pronunciation: 'tha', image: getLetterImage('ث', 'arabic') },
      { char: 'ج', pronunciation: 'jim', image: getLetterImage('ج', 'arabic') },
      { char: 'ح', pronunciation: 'ha', image: getLetterImage('ح', 'arabic') },
      { char: 'خ', pronunciation: 'kha', image: getLetterImage('خ', 'arabic') },
      { char: 'د', pronunciation: 'dal', image: getLetterImage('د', 'arabic') },
      { char: 'ذ', pronunciation: 'dhal', image: getLetterImage('ذ', 'arabic') },
      { char: 'ر', pronunciation: 'ra', image: getLetterImage('ر', 'arabic') },
      { char: 'ز', pronunciation: 'zay', image: getLetterImage('ز', 'arabic') },
      { char: 'س', pronunciation: 'sin', image: getLetterImage('س', 'arabic') },
      { char: 'ش', pronunciation: 'shin', image: getLetterImage('ش', 'arabic') },
      { char: 'ص', pronunciation: 'sad', image: getLetterImage('ص', 'arabic') },
      { char: 'ض', pronunciation: 'dad', image: getLetterImage('ض', 'arabic') },
      { char: 'ط', pronunciation: 'ta', image: getLetterImage('ط', 'arabic') },
      { char: 'ظ', pronunciation: 'za', image: getLetterImage('ظ', 'arabic') },
      { char: 'ع', pronunciation: 'ayn', image: getLetterImage('ع', 'arabic') },
      { char: 'غ', pronunciation: 'ghayn', image: getLetterImage('غ', 'arabic') },
      { char: 'ف', pronunciation: 'fa', image: getLetterImage('ف', 'arabic') },
    ],
    numbers: [
      { char: '1', text: '١ (wahid)', pronunciation: 'wah-heed', image: getNumberImage('1') },
      { char: '2', text: '٢ (ithnan)', pronunciation: 'ith-nahn', image: getNumberImage('2') },
      { char: '3', text: '٣ (thalatha)', pronunciation: 'tha-lah-tha', image: getNumberImage('3') },
      { char: '4', text: '٤ (arba\'a)', pronunciation: 'ar-bah-ah', image: getNumberImage('4') },
      { char: '5', text: '٥ (khamsa)', pronunciation: 'kham-sah', image: getNumberImage('5') },
      { char: '6', text: '٦ (sitta)', pronunciation: 'sit-tah', image: getNumberImage('6') },
      { char: '7', text: '٧ (sab\'a)', pronunciation: 'sab-ah', image: getNumberImage('7') },
      { char: '8', text: '٨ (thamaniya)', pronunciation: 'tha-ma-nee-yah', image: getNumberImage('8') },
      { char: '9', text: '٩ (tis\'a)', pronunciation: 'tis-ah', image: getNumberImage('9') },
      { char: '10', text: '١٠ (\'ashara)', pronunciation: 'ah-shah-rah', image: getNumberImage('10') },
      { char: '11', text: '١١ (ahada \'ashar)', pronunciation: 'ah-hah-dah ah-shar', image: getNumberImage('11') },
      { char: '12', text: '١٢ (ithna \'ashar)', pronunciation: 'ith-nah ah-shar', image: getNumberImage('12') },
      { char: '13', text: '١٣ (thalatha \'ashar)', pronunciation: 'tha-lah-tha ah-shar', image: getNumberImage('13') },
      { char: '14', text: '١٤ (arba\'a \'ashar)', pronunciation: 'ar-bah-ah ah-shar', image: getNumberImage('14') },
      { char: '15', text: '١٥ (khamsa \'ashar)', pronunciation: 'kham-sah ah-shar', image: getNumberImage('15') },
      { char: '16', text: '١٦ (sitta \'ashar)', pronunciation: 'sit-tah ah-shar', image: getNumberImage('16') },
      { char: '17', text: '١٧ (sab\'a \'ashar)', pronunciation: 'sab-ah ah-shar', image: getNumberImage('17') },
      { char: '18', text: '١٨ (thamaniya \'ashar)', pronunciation: 'tha-ma-nee-yah ah-shar', image: getNumberImage('18') },
      { char: '19', text: '١٩ (tis\'a \'ashar)', pronunciation: 'tis-ah ah-shar', image: getNumberImage('19') },
      { char: '20', text: '٢٠ (\'ishrun)', pronunciation: 'eesh-roon', image: getNumberImage('20') },
    ],
  },
  // ITALIAN
  {
    language: 'Italian',
    langCode: 'it-IT',
    audioVerified: true,
    description: 'Learn the Italian alphabet (21 letters) and numbers 1-20. Italian uses the Latin alphabet.',
    specialNotes: 'Italian alphabet has 21 letters (J, K, W, X, Y are only used in foreign words).',
    letters: [
      { char: 'A', pronunciation: 'ah', image: getLetterImage('A', 'italian') },
      { char: 'B', pronunciation: 'bee', image: getLetterImage('B', 'italian') },
      { char: 'C', pronunciation: 'chee', image: getLetterImage('C', 'italian') },
      { char: 'D', pronunciation: 'dee', image: getLetterImage('D', 'italian') },
      { char: 'E', pronunciation: 'eh', image: getLetterImage('E', 'italian') },
      { char: 'F', pronunciation: 'effe', image: getLetterImage('F', 'italian') },
      { char: 'G', pronunciation: 'jee', image: getLetterImage('G', 'italian') },
      { char: 'H', pronunciation: 'acca', image: getLetterImage('H', 'italian') },
      { char: 'I', pronunciation: 'ee', image: getLetterImage('I', 'italian') },
      { char: 'L', pronunciation: 'elle', image: getLetterImage('L', 'italian') },
      { char: 'M', pronunciation: 'emme', image: getLetterImage('M', 'italian') },
      { char: 'N', pronunciation: 'enne', image: getLetterImage('N', 'italian') },
      { char: 'O', pronunciation: 'oh', image: getLetterImage('O', 'italian') },
      { char: 'P', pronunciation: 'pee', image: getLetterImage('P', 'italian') },
      { char: 'Q', pronunciation: 'koo', image: getLetterImage('Q', 'italian') },
      { char: 'R', pronunciation: 'erre', image: getLetterImage('R', 'italian') },
      { char: 'S', pronunciation: 'esse', image: getLetterImage('S', 'italian') },
      { char: 'T', pronunciation: 'tee', image: getLetterImage('T', 'italian') },
      { char: 'U', pronunciation: 'oo', image: getLetterImage('U', 'italian') },
      { char: 'V', pronunciation: 'vee', image: getLetterImage('V', 'italian') },
      { char: 'Z', pronunciation: 'zeta', image: getLetterImage('Z', 'italian') },
    ],
    numbers: [
      { char: '1', text: 'uno', pronunciation: 'oo-noh', image: getNumberImage('1') },
      { char: '2', text: 'due', pronunciation: 'doo-eh', image: getNumberImage('2') },
      { char: '3', text: 'tre', pronunciation: 'treh', image: getNumberImage('3') },
      { char: '4', text: 'quattro', pronunciation: 'kwah-troh', image: getNumberImage('4') },
      { char: '5', text: 'cinque', pronunciation: 'cheen-kweh', image: getNumberImage('5') },
      { char: '6', text: 'sei', pronunciation: 'say', image: getNumberImage('6') },
      { char: '7', text: 'sette', pronunciation: 'set-teh', image: getNumberImage('7') },
      { char: '8', text: 'otto', pronunciation: 'oh-toh', image: getNumberImage('8') },
      { char: '9', text: 'nove', pronunciation: 'noh-veh', image: getNumberImage('9') },
      { char: '10', text: 'dieci', pronunciation: 'dee-eh-chee', image: getNumberImage('10') },
      { char: '11', text: 'undici', pronunciation: 'oon-dee-chee', image: getNumberImage('11') },
      { char: '12', text: 'dodici', pronunciation: 'doh-dee-chee', image: getNumberImage('12') },
      { char: '13', text: 'tredici', pronunciation: 'treh-dee-chee', image: getNumberImage('13') },
      { char: '14', text: 'quattordici', pronunciation: 'kwah-tor-dee-chee', image: getNumberImage('14') },
      { char: '15', text: 'quindici', pronunciation: 'kween-dee-chee', image: getNumberImage('15') },
      { char: '16', text: 'sedici', pronunciation: 'seh-dee-chee', image: getNumberImage('16') },
      { char: '17', text: 'diciassette', pronunciation: 'dee-chah-set-teh', image: getNumberImage('17') },
      { char: '18', text: 'diciotto', pronunciation: 'dee-choht-toh', image: getNumberImage('18') },
      { char: '19', text: 'diciannove', pronunciation: 'dee-chahn-noh-veh', image: getNumberImage('19') },
      { char: '20', text: 'venti', pronunciation: 'ven-tee', image: getNumberImage('20') },
    ],
  },
];

async function seedAlphabets() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing alphabet data
    await Alphabet.deleteMany({});
    console.log('🗑️  Cleared existing alphabet data');

    // Insert new alphabet data
    const inserted = await Alphabet.insertMany(alphabetData);
    console.log(`✅ Seeded ${inserted.length} languages with alphabet data`);

    for (const alpha of inserted) {
      console.log(`  📚 ${alpha.language}: ${alpha.letters.length} letters, ${alpha.numbers.length} numbers`);
    }

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding alphabets:', error);
    process.exit(1);
  }
}

seedAlphabets();

